package com.example.buhalo.lazyir.service;


public enum BackgroundServiceCmds {
    START_UDP_LISTENER,
    STOP_UDP_LISTENER,
    START_SEND_PERIODICALLY_UDP,
    STOP_SENDING_PERIODICALLY_UDP,
    CLOSE_ALL_TCP_CONNECTIONS,
    SUBMIT_TASK,
    SEND_TO_ALL,
    DESTROY,
    START_TASKS,
    CACHE_CONNECT,
    REGISTER_BROADCASTS,
    ON_DEVICE_DISCONNECTED,
    REMOVE_CLIP_BOARD_LISTENER,
    START_CLIPBOARD_LISTENER
}
